# Generated by Django 5.0.6 on 2024-06-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_app/')),
                ('tittle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('user_review', models.CharField(default='Good', max_length=30)),
                ('borrow_price', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('dates', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('comment_here', models.TextField(max_length=100)),
                ('show_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book_app.bookmodel')),
            ],
        ),
    ]
