# Generated by Django 5.0.6 on 2024-06-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_borrowedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='remain',
            field=models.IntegerField(default=0),
        ),
    ]
