# Generated by Django 5.0.6 on 2024-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_borrowedbook_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
